<?php 
require_once('connect.php');
require_once('selects.php');
?>

<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="css/main.css">

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<!-- <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script> -->
	<script type="text/javascript" src="js/main.js"></script>

</head>
<body>

	<div style="width: 30%; height: auto; margin-left: 33%; margin-top: 25px;">

		<form method="post" action="generator.php">
			<div class="form-group">
			    <label for="name">Имя</label>
				<input class="required form-control" type="text" name="name">
				<span class="not_value">Поле не заполнено!</span>
			</div>
			<div class="form-group">
			    <label for="last_name">Фамилия</label>
				<input class="required form-control" type="text" name="last_name">
				<span class="not_value">Поле не заполнено!</span>
			</div>
			<div class="form-group">
			    <label for="phone">Телефон</label>
				<input class="required form-control" type="text" name="phone">
				<span class="not_value">Поле не заполнено!</span>
			</div>
	  		<div class="form-group">
			    <label for="email">Email</label>
			    <input type="email" id="email" class="required form-control" name="email" >
			    <span class="email_val">Введенный адрес не корректный</span>
			    <span class="not_value">Поле не заполнено!</span>
	  		</div>
	  		<div class="form-group">
			    <label for="shares">Акции</label>
			    <select name="shares" class="required form-control">
			    	<option selected disabled value>Выбрать акцию</option>
					<?php foreach ($shares as $value) : ?>
					    <option value=<?= $value['id']?>><?= $value['shares']?></option>
					<? endforeach; ?>
			    </select>
			    <span class="not_value">Поле не заполнено!</span>
			</div>
	  		
	  		<button type="submit" class="validation btn btn-primary">Генерировать код</button>
		</form>
	</div>

</body>
</html>